from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


NotificationLevel = Literal[
    "info",
    "success",
    "warning",
    "error",
]


@dataclass(slots=True)
class ChatNotification:
    """
    Represents a notification generated by Cipher.
    """

    title: str
    message: str
    level: NotificationLevel = "info"
    created_at: datetime = field(
        default_factory=datetime.now
    )
    read: bool = False


class ChatNotificationService:
    """
    In-memory notification manager.

    Future GUI components can subscribe to this service
    to display toast notifications or a notification
    center without changing the public API.
    """

    def __init__(self):

        self._notifications: list[ChatNotification] = []

    # --------------------------------------------------

    def add(
        self,
        title: str,
        message: str,
        level: NotificationLevel = "info",
    ) -> ChatNotification:

        notification = ChatNotification(
            title=title,
            message=message,
            level=level,
        )

        self._notifications.insert(
            0,
            notification,
        )

        return notification

    # --------------------------------------------------

    def list(self) -> list[ChatNotification]:

        return list(self._notifications)

    # --------------------------------------------------

    def unread(self) -> list[ChatNotification]:

        return [
            notification
            for notification in self._notifications
            if not notification.read
        ]

    # --------------------------------------------------

    def mark_read(
        self,
        notification: ChatNotification,
    ):

        notification.read = True

    # --------------------------------------------------

    def mark_all_read(self):

        for notification in self._notifications:
            notification.read = True

    # --------------------------------------------------

    def clear(self):

        self._notifications.clear()

    # --------------------------------------------------

    def count(self) -> int:

        return len(self._notifications)

    # --------------------------------------------------

    def unread_count(self) -> int:

        return len(self.unread())


chat_notification_service = ChatNotificationService()